inherit_from: voxelization/configs/train_skullfix.yaml

train:
  gpu: 0  # GPU to use for inference

data:
  dset: SkullFix
  path: datasets/SkullFix/results/syn  # Path to results folder of point cloud diffusion model (SkullFix)

generation:
  generation_dir: gen_skullfix
  num_ensemble: 5
  save_ensemble_implants: False  # False: Just for mean implant generation; True: Enables variance map and different implant designs
  compute_eval_metrics: True    # Set True to automatically compute the evaluation metrics for the generated implants

test:
  model_file: voxelization/out/skullfix/model_best.pt  # Path to model